name: Install Package From Artifact

on:
  workflow_run:
    workflows: ["Main CI Pipeline"]
    types:
      - completed

jobs:
  install_package:
    runs-on: ubuntu-latest

    steps:
      - name: Download wheel artifact
        uses: actions/download-artifact@v4
        with:
          name: calculator-wheel
          path: wheel-download

      - name: Install wheel
        run: pip install wheel-download/*.whl

      - name: Verify installation
        run: python -c "import calculator; print('Installed Successfully')"
