name: Install Calculator Package From Artifact

on:
  workflow_run:
    workflows: ["Awesome Calculator CI build"]
    types:
      - completed

jobs:
  install_package:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloaded-dist

      - name: Show downloaded files
        run: ls -R downloaded-dist

      - name: Install wheel
        run: |
          pip install $(find downloaded-dist -name "*.whl" | head -n 1)

      - name: Verify installation
        run: |
          pip show awesomecalculator || echo "Package not found"
