name: Main CI Pipeline

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  lint:
    name: Pre-commit + Pylint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install lint tools
        run: pip install pylint

      - name: Run pylint
        run: pylint src || true


  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install pytest
        run: pip install pytest

      - name: Add src to PYTHONPATH
        run: echo "PYTHONPATH=$PWD/src" >> $GITHUB_ENV

      - name: Run tests
        run: pytest -q


  acceptance_tests:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    needs: unit_tests

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install pytest
        run: pip install pytest

      - name: Add src to PYTHONPATH
        run: echo "PYTHONPATH=$PWD/src" >> $GITHUB_ENV

      - name: Run acceptance tests
        run: pytest -q --disable-warnings --maxfail=1
        
  build_package:
    name: Build Package
    needs: acceptance_tests
    uses: ./.github/workflows/python-package.yml
